### ISSUE TITLE
TODO: Implement generators with params

### ISSUE THREAD

**Issue by VBardin08** [Bardin08/db-seeder#26]
See the code near this line: https://github.com/Bardin08/db-seeder/blob/b52f39a23c57e57342a8a7e00427f121cb6bbbb6/DbSeeder/Data/Bogus/BogusUtilities.cs#L62

Also, look for the number of this issue in the project code base.

**Comment by Bardin08** [comment]
To get that work we have to define a reliable way how to generate parameters for the generators according to the constraints (#27)
